// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAujwFMCXjkMKd_Tu6fdpreaT_PZGfHK5A',
    appId: '1:824322472315:web:e88ab8ac288ba730f025de',
    messagingSenderId: '824322472315',
    projectId: 'abnayiy-wallet',
    authDomain: 'abnayiy-wallet.firebaseapp.com',
    storageBucket: 'abnayiy-wallet.firebasestorage.app',
    measurementId: 'G-7EVN7Y8KDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQDE_CPi49912oJOfsc9s-N9gBdQ8tg6g',
    appId: '1:824322472315:android:e51eff5e0a3b2c77f025de',
    messagingSenderId: '824322472315',
    projectId: 'abnayiy-wallet',
    storageBucket: 'abnayiy-wallet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV1indGpnKMpmlLMd9o6AYjCd9x6yC8qk',
    appId: '1:824322472315:ios:a7ca25ca2e470ebaf025de',
    messagingSenderId: '824322472315',
    projectId: 'abnayiy-wallet',
    storageBucket: 'abnayiy-wallet.firebasestorage.app',
    iosBundleId: 'com.example.abnayiyWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV1indGpnKMpmlLMd9o6AYjCd9x6yC8qk',
    appId: '1:824322472315:ios:a7ca25ca2e470ebaf025de',
    messagingSenderId: '824322472315',
    projectId: 'abnayiy-wallet',
    storageBucket: 'abnayiy-wallet.firebasestorage.app',
    iosBundleId: 'com.example.abnayiyWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAujwFMCXjkMKd_Tu6fdpreaT_PZGfHK5A',
    appId: '1:824322472315:web:e79f78e41a5cfb90f025de',
    messagingSenderId: '824322472315',
    projectId: 'abnayiy-wallet',
    authDomain: 'abnayiy-wallet.firebaseapp.com',
    storageBucket: 'abnayiy-wallet.firebasestorage.app',
    measurementId: 'G-F7T6DJJ9E5',
  );
}
